version: '3'
services:
  order-service:
    build: ./
    environment:
      - OTEL_TRACES_EXPORTER=logging
      - OTEL_METRICS_EXPORTER=logging
      - OTEL_LOGS_EXPORTER=logging
      - OTEL_METRIC_EXPORT_INTERVAL=15000
    ports:
      - "8080:8080"